version: '3.8'

services:
  proxy:
    build: .
    container_name: proxy-server
    ports:
      - "3128-4128:3128-4128"
      - "80:80"
      - "443:443"
    volumes:
      - ./config:/etc/haproxy
      - ./certs:/etc/haproxy/certs
      - ./logs:/var/log/haproxy
    environment:
      - PROXY_COUNT=1000
      - BASE_PORT=3128
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_max_syn_backlog=65536
      - net.core.somaxconn=65536
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge
